### ISSUE TITLE
회원이 선호하는 술 추가,삭제 구현

### ISSUE THREAD

**Issue by wyu950** [great-sprout/PyeonSool#151]
## 설명
마이 페이지에서  상세페이지에서 Like버튼 클릭하면 그정보가 내Like리스트에 등록되고 등록된 이미지에 X버튼 눌르면 삭제

## 작업 분류
- [ ] 회원이 선호하는 술 추가
- [ ] 회원이 선호하는 술 삭제

**Comment by JunYoung-C** [comment]
제가 만든 기능과 동일한 이슈면, 이슈 삭제해주세요!
